km = input("introduza os km percurridos: ")
litros = input("introduza os litros gastos: ")
kml = (float(km)) / (float(litros))
lkm = (float(litros)) / (float(km))
print("o seu consumo foi ", kml, "Km/l")
print("o seu consumo foi ", lkm, "l/km")    